### PR TITLE
nethttp: implement http.Hijacker in response wrapper

### PR DESCRIPTION
**Pull request by kujenga**
This is needed in order for users of this package to implement websocket
support, as without it, the statusCodeTracker struct does not implement
the correct interface because it knows nothing about the underlying
implementation of it's embedded http.ResponseWriter.

For reference, many other project have had this same issue, here's a
list of some found in a quick search for the issue, I'm sure there are
others as well:
- https://github.com/census-instrumentation/opencensus-go/issues/642
- https://github.com/go-chi/chi/issues/131
- https://github.com/NYTimes/gziphandler/issues/26
- https://github.com/mholt/caddy/issues/133
- https://github.com/emicklei/go-restful/issues/354

### CODE REVIEW

**Comment by yurishkuro** [comment]
please see #11

**Comment by kujenga** [comment]
Ah! Thank you for pointing that out, I'd missed that. @yurishkuro do you plan to move forward with merging that PR? Or should I leave this in place as a possible alternative?

**Comment by yurishkuro** [comment]
As far as I can tell there are issues with both PRs. The previous one is too heavy from perf point of view. Yours is functionally incorrect because it makes the object always look like it's a Hijacker, even when the underlying object wasn't (in other words it may cause unexpected behavior in the applications that do something special ok m case of a Hijacker).

Ideally someone should implement something similar to httpsnoop, but without additional overhead. I haven't looked at httpsnoop in a while, maybe it was refactored to separate the interfaces supposed from other functionally.

**Comment by yurishkuro** [comment]
I suggest looking at httpsnoop implementation, it does use different structs, but because the number of their permutations is pretty large I think it auto-generates the code for them.

**Comment by kujenga** [comment]
@yurishkuro what are your thoughts on the best way to move forward with this functionality? Shall I close this PR out in favor of another? It sounds like https://github.com/opentracing-contrib/go-stdlib/pull/26 is the most in line with what you are looking for.

It would be great to have this issue resolved.

**Comment by yurishkuro** [comment]
I think #26 is a better approach

**Comment by kujenga** [comment]
Closing this in favor of https://github.com/opentracing-contrib/go-stdlib/pull/26

**Pull request closed without merging**
