### PR TITLE
Change example to be more in line with common OpenTracing context propagation

### PR DESCRIPTION
**Pull request by yurishkuro**
Also change example to be more in line with common OpenTracing context propagation

### CODE REVIEW

**Comment by yurishkuro** [comment]
@dominikh

**Comment by dominikh** [comment]
I'm not sure this is right. Even when there is a parent span, we want a span that describes the HTTP client request as a whole. The root span will have a number of children, one per request, with >1 children due to HTTP redirects. The root span is also the span that will be finished by `(*Tracer).Finish`. Reusing the parent span, and not finishing the root span after the request itself is done, will produce inaccurate traces.

**Comment by yurishkuro** [comment]
how about this? I restored the root logic, but renamed the span to HTTP Client, and removed RPC tag from it, because that tag isn't really a part of a client-server exchange (e.g. in Zipkin case it would create meaningless ClientSend/Receive).

**Comment by dominikh** [comment]
@yurishkuro Do you agree with the following rework of your PR?

```
From 33b4df363942a1af7dba8ddcec34051f035e8a00 Mon Sep 17 00:00:00 2001
From: Yuri Shkuro <ys@uber.com>
Date: Tue, 4 Oct 2016 21:55:51 +0200
Subject: [PATCH 1/2] nethttp: do not mark root span as RPC, rename to "HTTP
 Client"

The root span does not constitute an RPC itself. Only the actual HTTP
requests under the client are RPCs.

Also renames the span from "HTTP" to "HTTP Client".
---
 nethttp/client.go | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

diff --git a/nethttp/client.go b/nethttp/client.go
index 7b5f3b3..698d7a4 100644
--- a/nethttp/client.go
+++ b/nethttp/client.go
@@ -111,8 +111,7 @@ func (h *Tracer) start(req *http.Request) opentracing.Span {
                if parent != nil {
                        spanctx = parent.Context()
                }
-               root := h.tr.StartSpan("HTTP", opentracing.ChildOf(spanctx))
-               ext.SpanKindRPCClient.Set(root)
+               root := h.tr.StartSpan("HTTP Client", opentracing.ChildOf(spanctx))
                h.root = root
        }
 
-- 
2.10.0


From 75e37ae3e209c490d2aa67d8a31fb302fdc38cba Mon Sep 17 00:00:00 2001
From: Yuri Shkuro <ys@uber.com>
Date: Tue, 4 Oct 2016 21:59:12 +0200
Subject: [PATCH 2/2] nethttp: improve example code

---
 nethttp/client.go | 29 +++++++++++++++++------------
 1 file changed, 17 insertions(+), 12 deletions(-)

diff --git a/nethttp/client.go b/nethttp/client.go
index 698d7a4..1222ece 100644
--- a/nethttp/client.go
+++ b/nethttp/client.go
@@ -33,19 +33,24 @@ type Transport struct {
 //
 // Example:
 //
-//  client := &http.Client{Transport: &nethttp.Transport{}}
-//     req, err := http.NewRequest("GET", "http://google.com", nil)
-//     if err != nil {
-//             log.Fatal(err)
-//     }
-//     req = req.WithContext(opentracing.ContextWithSpan(req.Context(), parentSpan))
-//     req, ht := nethttp.TraceRequest(tracer, req)
-//     res, err := client.Do(req)
-//     if err != nil {
-//             log.Fatal(err)
+//     func AskGoogle(ctx context.Context) error {
+//             client := &http.Client{Transport: &nethttp.Transport{}}
+//             req, err := http.NewRequest("GET", "http://google.com", nil)
+//             if err != nil {
+//                     return err
+//             }
+//             req = req.WithContext(ctx) // extend existing trace, if any
+//
+//             req, ht := nethttp.TraceRequest(tracer, req)
+//             defer ht.Finish()
+//
+//             res, err := client.Do(req)
+//             if err != nil {
+//                     return err
+//             }
+//             res.Body.Close()
+//             return nil
 //     }
-//     res.Body.Close()
-//     ht.Finish()
 func TraceRequest(tr opentracing.Tracer, req *http.Request) (*http.Request, *Tracer) {
        ht := &Tracer{tr: tr}
        ctx := httptrace.WithClientTrace(req.Context(), ht.clientTrace())
-- 
2.10.0

```

**Comment by dominikh** [comment]
Merged as 33b4df3 and 75e37ae, thank you!

**Comment by yurishkuro** [comment]
@dominikh https://medium.com/@YuriShkuro/tracing-http-request-latency-in-go-with-opentracing-7cc1282a100a#.qeh3t5147

**Pull request closed without merging**
