### PR TITLE
feat: Tracer in Transport

### LINKED ISSUE #29: RoundTripper should work out of the box.
In following example:
```go
	client := &http.Client{Transport: &nethttp.Transport{}}
	req, err := http.NewRequest("GET", "http://google.com", nil)
	if err != nil {
		return err
	}
	req = req.WithContext(ctx) // extend existing trace, if any

	req, ht := nethttp.TraceRequest(tracer, req)
	defer ht.Finish()

	res, err := client.Do(req)
	if err != nil {
		return err
	}
	res.Body.Close()
	return nil
```

nethttp.TraceRequest is extra. It is ok for people wanting greater control, but it should default to using GlobalTracer(). 

Similar to opencensus variant, ochttp, https://github.com/census-instrumentation/opencensus-go/tree/master/plugin/ochttp, things work out of the box. Just using their server middleware and their roundtripper plus adding parent request headers to context (via ```req = req.WithContext(parent.Context())```)

### PR DESCRIPTION
**Pull request by shaxbee**
Add `Tracer` argument to `nethttp.Transport`.
Fixes #29

### CODE REVIEW

**Comment by shaxbee** [comment]
Hold on merging, there is sp state in Tracer, need to fix this to avoid race condition.

**Comment by shaxbee** [comment]
Fixed and ready for review.

I would suggest small refactoring of Tracer clientOptions - instead making them public structure with simple public fields, as there is unnecessary overhead of applying functional options on each call plus it cannot be used without dedicated constructor. Let me know if i can make those changes.

**Comment by yurishkuro** [comment]
it would be a breaking change. Rather than refactoring it would have to be differently named constructor function

**Comment by shaxbee** [comment]
Alright, would current change be acceptable then?

**Comment by yurishkuro** [comment]
What happens to the `root` span created in `start()` function if the user does not call finish()?
```go
	req, ht := nethttp.TraceRequest(tracer, req)
	defer ht.Finish()
```

Also, the PR needs unit test for the new mode and update to the docs showing the alternative usage.

**Comment by wpjunior** [comment]
@shaxbee and @yurishkuro I had wrote a wrapper to put tracer inside the transport at tsuru.io.

You could see the code here: https://github.com/tsuru/tsuru/blob/main/net/opentracing.go#L29

I hope that will help to achieve this solution.

**Comment by yurishkuro** [comment]
closing old/stale PR

**Pull request closed without merging**
